# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node 18.x'
  inputs:
    versionSpec: 18.x
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
    options: '-Dcucumber.filter.tags="@UI" -DbrowserName="chromium" -Dheadless="true"'

- task: PublishCucumberReport@1
  inputs:
    jsonDir: 'target/cucumber-report'
    outputPath: 'target/cucumber-html-reports'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: 'Playwright-cucumber-html-report'
    title: 'Playwright-java-cucumber-html-report'


